/* oxlint-disable typescript/no-floating-promises -- node:test owns and awaits registered tests. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {beginOAuth,validateCallback,completeOAuth,redirectUri} from '../oauth.mjs';
import {activationDecision} from '../activation.mjs';
import {tokenHealth} from '../api.mjs';
test('official OAuth has an exact HTTPS callback and random state',()=>{const a=beginOAuth('123');const b=beginOAuth('123');assert.notEqual(a.session.state,b.session.state);const u=new URL(a.url);assert.equal(u.hostname,'www.instagram.com');assert.equal(u.searchParams.get('redirect_uri'),redirectUri);assert.equal(u.searchParams.get('scope').includes('instagram_business_content_publish'),true);assert.equal(u.searchParams.get('scope').includes('manage_messages'),false);});
test('callback rejects state, origin, path, decline and expired session',()=>{const {session}=beginOAuth('123',100);const u=new URL(redirectUri);u.searchParams.set('state',session.state);u.searchParams.set('code','test-code');assert.equal(validateCallback(u,session,200),'test-code');assert.throws(()=>validateCallback(u,{...session,state:'wrong'},200));assert.throws(()=>validateCallback(u,{...session,createdAt:-1000000},200));assert.throws(()=>validateCallback(u,{...session,redirectUri:'https://evil.example/callback'},200));u.searchParams.set('error','access_denied');assert.throws(()=>validateCallback(u,session,200));});
test('code and token exchanges occur server-side; only intended account accepted',async()=>{const {session}=beginOAuth('123');const u=new URL(redirectUri);u.searchParams.set('state',session.state);u.searchParams.set('code','test-code');let calls=0;const fetcher=async(url,init)=>{calls++;if(calls===1){assert.equal(url,'https://api.instagram.com/oauth/access_token');assert.equal(init.method,'POST');assert.equal(init.body.get('redirect_uri'),redirectUri);return Response.json({access_token:'short-token',user_id:'456'});}if(calls===2)return Response.json({access_token:'long-token',expires_in:5184000});return Response.json({user_id:'456',username:'cleverfindspicks'});};const c=await completeOAuth(u,session,'test-secret',{fetcher});assert.equal(c.userId,'456');assert.equal(c.token,'long-token');assert.equal(calls,3);});
test('one trial requires explicit review before daily operation',()=>{assert.equal(activationDecision({publishedCount:0,approved:false}),'TRIAL_PENDING');assert.equal(activationDecision({publishedCount:0,approved:false,force:true}),'ONE_TRIAL_ALLOWED');assert.equal(activationDecision({publishedCount:1,approved:false,force:true}),'TRIAL_REVIEW_REQUIRED');assert.equal(activationDecision({publishedCount:1,approved:true}),'DAILY_ENABLED');assert.equal(activationDecision({publishedCount:1,approved:false,uncertain:true}),'RECONCILE_ONLY');});
test('invalid token expiration cannot look CONNECTED',()=>{assert.equal(tokenHealth({token:'fixture',userId:'456',expiresAt:'invalid'}),'TOKEN_EXPIRING');});
test('a different Instagram account is rejected before credentials are saved',async()=>{const {session}=beginOAuth('123');const u=new URL(redirectUri);u.searchParams.set('state',session.state);u.searchParams.set('code','test-code');let calls=0;const fetcher=async()=>{calls++;return Response.json(calls===1?{access_token:'short-token'}:calls===2?{access_token:'long-token',expires_in:5184000}:{user_id:'456',username:'wrong-account'});};await assert.rejects(completeOAuth(u,session,'test-secret',{fetcher}),/not cleverfindspicks/);});
