/* oxlint-disable typescript/no-floating-promises -- node:test awaits registered tests. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {visibleCatalogueFinds,visibleInstagramFinds,searchInstagramFinds} from '../hub-policy.mjs';
import {motionTexts,motionSceneDurations} from '../motion-creative.mjs';
const product={slug:'sink',productId:'123',shortName:'Sink organiser',summary:'Keep essentials together',cluster:'tiny-kitchen',image:'original',displayImage:'/products/verified/sink.jpg',productImageVerified:true,affiliateDestinationVerified:true};
const record={productSlug:'sink',productId:'123',mediaId:'m',publishedAt:'2026-09-15',currencyVerified:true,productApproved:true,publicationStatus:'LIVE',caption:'Sponge holder',trackingId:'ig-original'};
test('hub excludes test/deleted/disabled and Pinterest-only products',()=>{for(const patch of [{publicationStatus:'TEST'},{publicationStatus:'DELETED'},{deleted:true},{test:true},{currencyVerified:false},{mediaId:null},{productId:'wrong'}])assert.equal(visibleInstagramFinds([{...record,...patch}],[product]).length,0);assert.equal(visibleInstagramFinds([record],[{...product,ctaDisabled:true}]).length,0);assert.equal(visibleInstagramFinds([],[product]).length,0);});
test('latest ordering, deduplication and original tracking retained',()=>{const result=visibleInstagramFinds([{...record,publishedAt:'2026-01-01'},record],[product]);assert.equal(result.length,1);assert.equal(result[0].record.publishedAt,'2026-09-15');assert.equal(result[0].record.trackingId,'ig-original');});
test('empty Instagram hub falls back only to active fully verified catalogue products',()=>{const eligible={...product,catalogueCurrencyVerified:true,publishedAt:'2026-09-15'};assert.deepEqual(visibleCatalogueFinds([eligible]).map(row=>row.slug),['sink']);for(const patch of [{catalogueCurrencyVerified:false},{affiliateDestinationVerified:false},{productImageVerified:false},{ctaDisabled:true},{rejected:true},{deleted:true}])assert.equal(visibleCatalogueFinds([{...eligible,...patch}]).length,0);});
test('instant search covers title, cluster, usefulness and caption',()=>{const rows=[{record,product}];for(const query of ['sink','tiny-kitchen','essentials','sponge'])assert.equal(searchInstagramFinds(rows,query).length,1);assert.equal(searchInstagramFinds(rows,'unrelated').length,0);});
test('V2 motion has four scenes, 9 seconds, product-specific copy and no creative URL or price',()=>{assert.equal(motionSceneDurations.reduce((a,b)=>a+b),9);const {copy,scenes}=motionTexts({productId:'123',title:'3-in-1 Sink Organiser',cluster:'kitchen'});assert.equal(scenes.length,4);assert.equal(/https?:|github\.io|£/.test(scenes.flat().join(' ')),false);assert.ok(copy.caption.startsWith('Ad / affiliate.'));assert.match(copy.caption,/#SinkOrganisation/);assert.deepEqual(scenes[3],['See today’s find — link in bio']);assert.doesNotMatch(scenes.flat().join(' '),/practical find for smaller homes/i);});
