export type Product = {
  slug: string;
  eyebrow: string;
  name: string;
  shortName: string;
  summary: string;
  price: string;
  positiveFeedback: string;
  recentVolume: string;
  image: string;
  pinImage?: string;
  affiliateUrl: string;
  publishedAt: string;
  bestFor: string[];
  checks: string[];
};

export const checkedAt = '11 September 2026';

export const products: Product[] = [
  {
    slug: 'pull-out-under-sink-organiser',
    eyebrow: 'KITCHEN & BATHROOM',
    name: '2-tier pull-out under-sink organiser',
    shortName: 'Pull-out under-sink organiser',
    summary: 'A sliding two-level rack that turns an awkward cupboard into storage you can actually reach.',
    price: '£41.99',
    positiveFeedback: '98%',
    recentVolume: '2,265',
    image: 'https://cleverfindspicks.github.io/products/pull-out-under-sink-organiser.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/e/_c3jFcknT',
    publishedAt: '2026-09-07T17:30:00Z',
    bestFor: ['Narrow kitchen cupboards', 'Cleaning-product storage', 'Renters who want a removable setup'],
    checks: ['Measure around your pipework before ordering.', 'Check the selected size and delivery estimate at checkout.', 'Compare the delivered price, not the headline item price.'],
  },
  {
    slug: 'wardrobe-clothes-organiser',
    eyebrow: 'WARDROBE',
    name: 'Foldable wardrobe clothes organiser',
    shortName: 'Wardrobe clothes organiser',
    summary: 'A lightweight divider for keeping jeans, jumpers and T-shirts visible instead of stacked into one pile.',
    price: '£1.65',
    positiveFeedback: '98%',
    recentVolume: '15,485',
    image: 'https://cleverfindspicks.github.io/products/wardrobe-clothes-organiser.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/e/_c4pY9FdF',
    publishedAt: '2026-09-07T17:45:00Z',
    bestFor: ['Small wardrobes', 'Separating everyday clothes', 'Low-cost organisation experiments'],
    checks: ['The displayed price may apply to one size or quantity.', 'Measure your shelf or drawer first.', 'Check material and buyer photos before choosing a variant.'],
  },
  {
    slug: 'expandable-spice-drawer-organiser',
    eyebrow: 'KITCHEN DRAWERS',
    name: 'Expandable acrylic spice drawer organiser',
    shortName: 'Expandable spice drawer organiser',
    summary: 'A tiered, adjustable tray that keeps spice jars visible at a glance instead of hidden at the back of a drawer.',
    price: '£45.81',
    positiveFeedback: '98%',
    recentVolume: '795',
    image: 'https://cleverfindspicks.github.io/products/expandable-spice-drawer-organiser.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0JxwaiKJK0fp7R0dVPhpNcOcJONfNQknE2uqVl3b7AuKmytkZ1vP0Cq',
    publishedAt: '2026-09-08T12:00:00Z',
    bestFor: ['Keeping spice labels visible', 'Shallow kitchen drawers', 'Small kitchens with limited cupboard space'],
    checks: ['Measure the drawer width and depth before ordering.', 'Confirm the selected two-tier or four-tier option.', 'Compare the final delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'folding-wall-hanging-laundry-basket',
    eyebrow: 'LAUNDRY & BATHROOM',
    name: 'Folding wall-hanging laundry basket',
    shortName: 'Folding laundry basket',
    summary: 'A collapsible mesh hamper that hangs out of the way and folds down when a small bathroom or utility area needs its floor space back.',
    price: '£24.13',
    positiveFeedback: '98%',
    recentVolume: '6,285',
    image: 'https://cleverfindspicks.github.io/products/folding-wall-hanging-laundry-basket.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0JxROAOd4KPej6F4x0XuhgRltQ7I09a1p8iVdl0cTi8DtLaveHMmL7L',
    publishedAt: '2026-09-08T19:00:00Z',
    bestFor: ['Small bathrooms', 'Utility cupboards', 'Keeping laundry off the floor'],
    checks: ['Confirm the selected size and hanging-frame option.', 'Check the fixing method suits your wall or door.', 'Compare the final delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'non-slip-slim-clothes-hangers-set',
    eyebrow: 'WARDROBE SPACE',
    name: '10-piece non-slip slim clothes hanger set',
    shortName: 'Slim non-slip clothes hangers',
    summary: 'A coordinated set of slim hangers that reduces visual clutter and helps a compact wardrobe fit more everyday clothes.',
    price: '£55.47',
    positiveFeedback: '98%',
    recentVolume: '748',
    image: 'https://cleverfindspicks.github.io/products/non-slip-slim-clothes-hangers-set.jpeg',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0JxheqIaC7rIUaXrhn5vOpmD4E0KzjLvnExCSpKmJaEYgG7xfGE1GQL',
    publishedAt: '2026-09-09T12:00:00Z',
    bestFor: ['Compact wardrobes', 'Keeping shirts from slipping', 'Creating a consistent hanging layout'],
    checks: ['Confirm the quantity and hanger dimensions for the selected option.', 'Check the maximum supported garment weight.', 'Compare the final delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'adjustable-cutlery-drawer-organiser',
    eyebrow: 'KITCHEN DRAWERS',
    name: 'Adjustable cutlery drawer organiser',
    shortName: 'Adjustable cutlery drawer organiser',
    summary: 'An expandable tray that separates everyday cutlery and utensils while adapting to the width of a compact kitchen drawer.',
    price: '£125.15',
    positiveFeedback: '98%',
    recentVolume: '4,205',
    image: 'https://cleverfindspicks.github.io/products/adjustable-cutlery-drawer-organiser.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0Jxw0Esx6Evh80rnDefQNNRiCFbFt9kdff28OUwIG3yFwSlfitnjBoe',
    publishedAt: '2026-09-09T16:00:00Z',
    bestFor: ['Narrow kitchen drawers', 'Separating cutlery and utensils', 'Adjusting storage without permanent fittings'],
    checks: ['Measure the internal drawer width, depth and height.', 'Confirm the selected size and included compartments.', 'Compare the final delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'adjustable-double-layer-shoe-slots',
    eyebrow: 'ENTRYWAY & WARDROBE',
    name: 'Adjustable double-layer shoe storage slots',
    shortName: 'Adjustable shoe storage slots',
    summary: 'Stackable plastic slots that give each pair a second level, helping a compact hallway or wardrobe store more shoes without a wider rack.',
    price: '£98.77',
    positiveFeedback: '95.6%',
    recentVolume: '751',
    image: 'https://cleverfindspicks.github.io/products/adjustable-double-layer-shoe-slots.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0JxRtiSrpzVqCNEuQKp39ihbozWn469RaK0tJMdLnhNMsF6OeZfcZN3',
    publishedAt: '2026-09-10T12:00:00Z',
    bestFor: ['Narrow entryways', 'Compact wardrobes', 'Doubling shelf space for everyday shoes'],
    checks: ['Confirm whether the selected option includes 7 or 100 pieces.', 'Measure the height available between shelves.', 'Compare the final delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'five-shelf-over-door-organiser',
    eyebrow: 'DOOR-BACK STORAGE',
    name: 'Five-shelf over-door storage organiser',
    shortName: 'Five-shelf over-door organiser',
    summary: 'A hanging five-tier organiser that turns the unused back of a door into accessible storage without taking up floor or cupboard space.',
    price: '£102.27',
    positiveFeedback: '97%',
    recentVolume: '90',
    image: 'https://cleverfindspicks.github.io/products/five-shelf-over-door-organiser.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0JxhFCO27oCQWy9iEZdILIg3hOm4u6gf7yFalscClnTsERGiUgnDQ21',
    publishedAt: '2026-09-10T16:00:00Z',
    bestFor: ['Small bedrooms', 'Bathroom essentials', 'Renters short on cupboard space'],
    checks: ['Measure the door width and available drop before ordering.', 'Confirm the hooks fit the thickness of your door.', 'Check the selected quantity, delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'five-tier-plastic-shelving-unit',
    eyebrow: 'FREESTANDING STORAGE',
    name: 'Five-tier plastic shelving unit',
    shortName: 'Five-tier storage shelves',
    summary: 'A slim freestanding rack that adds five open storage levels to a kitchen, utility room or garage without permanent fittings.',
    price: '£20.70',
    positiveFeedback: '100%',
    recentVolume: '52',
    image: 'https://cleverfindspicks.github.io/products/five-tier-plastic-shelving-unit.png',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0Jxg6HLdvrh6u1XDDlpl8V7aB2GMnFFdhyXmoumrqaTgC9AfeD17ALY',
    publishedAt: '2026-09-10T19:00:00Z',
    bestFor: ['Utility rooms', 'Kitchen overflow storage', 'Garages and compact cupboards'],
    checks: ['Confirm the selected shelf count and overall dimensions.', 'Check the stated load limit before storing heavy items.', 'Compare the final delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'twelve-piece-vacuum-storage-bag-set',
    eyebrow: 'SEASONAL STORAGE',
    name: '12-piece reusable vacuum storage bag set',
    shortName: 'Vacuum storage bag set',
    summary: 'A reusable set of vacuum-seal bags that compresses bulky duvets, pillows and seasonal clothes to free up wardrobe space.',
    price: '£208.54',
    positiveFeedback: '98%',
    recentVolume: '830',
    image: 'https://cleverfindspicks.github.io/products/twelve-piece-vacuum-storage-bag-set.jpg',
    pinImage: 'https://cleverfindspicks.github.io/pinterest/vacuum-storage-pin.png',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0Jxg0zjJ5oCsj8sSKxdkdExL24IJtjEOAN2p4H0IT6CDSR8X4gSbt1F',
    publishedAt: '2026-09-11T12:00:00Z',
    bestFor: ['Seasonal bedding', 'Bulky winter clothes', 'Small wardrobes and cupboards'],
    checks: ['Confirm the selected bag quantity and included sizes.', 'Check whether a hand or electric pump is included.', 'Compare the final delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'no-drill-bathroom-scale-storage-rack',
    eyebrow: 'BATHROOM STORAGE',
    name: 'No-drill wall-mounted bathroom scale storage rack',
    shortName: 'No-drill bathroom scale rack',
    summary: 'A compact adhesive wall rack that stores a bathroom scale upright, clearing the floor without drilling into tiles.',
    price: '£17.68',
    positiveFeedback: '98%',
    recentVolume: '5,966',
    image: 'https://cleverfindspicks.github.io/products/no-drill-bathroom-scale-storage-rack.jpg',
    pinImage: 'https://cleverfindspicks.github.io/pinterest/bathroom-scale-rack-pin.png',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0JxwsugEo6uflinDXyZZn4Mk0WYkWUr0OBq5p3kLR4vPtCZJSCvkZSf',
    publishedAt: '2026-09-11T16:00:00Z',
    bestFor: ['Compact bathrooms', 'Keeping a scale off the floor', 'Renters who want a no-drill option'],
    checks: ['Measure the thickness and width of your bathroom scale.', 'Confirm the adhesive is suitable for your wall or tile surface.', 'Compare the final delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'over-cabinet-door-multipurpose-hooks',
    eyebrow: 'NO-DRILL DOOR STORAGE',
    name: 'Multi-purpose over-cabinet door hook rack',
    shortName: 'Over-cabinet door hook rack',
    summary: 'A slim hook rail that slips over a cabinet door to keep tea towels, oven gloves and lightweight kitchen tools within reach without drilling.',
    price: '£14.09',
    positiveFeedback: '98%',
    recentVolume: '754',
    image: 'https://cleverfindspicks.github.io/products/over-cabinet-door-multipurpose-hooks.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0JyacREzRr0DIyjIuFFl4YD9UGMEEibFzrqal3CmiyegBDAzZxVKLUZ',
    publishedAt: '2026-09-12T12:00:00Z',
    bestFor: ['Compact kitchens', 'Renters who want no-drill storage', 'Keeping frequently used cloths and tools visible'],
    checks: ['Measure the cabinet-door thickness before ordering.', 'Confirm the hook depth will not obstruct shelves inside the cabinet.', 'Check the selected colour, delivered price and estimated arrival at checkout.'],
  },
  {
    slug: 'expandable-microwave-oven-storage-rack',
    eyebrow: 'KITCHEN COUNTER SPACE',
    name: 'Expandable microwave oven storage rack with hooks',
    shortName: 'Expandable microwave storage rack',
    summary: 'An adjustable carbon-steel shelf that uses the space above a microwave for spices and small kitchen essentials while keeping the worktop footprint compact.',
    price: '£126.67',
    positiveFeedback: '98%',
    recentVolume: '582',
    image: 'https://cleverfindspicks.github.io/products/expandable-microwave-oven-rack.jpg',
    affiliateUrl: 'https://s.click.aliexpress.com/s/fwx308cRD9Eny963e3KDdYxyIpNj8TXVr7saiF9Um5rMUg1kZtJALLnfa2LNXtiVgnxdD8Og6MmvwBoxhnSYQGM6r0c08U4TfX8DFGo7vviCuu3q62Q60OAhRZcqm3G8PtwM69xY7TOEWRrvulP5ukZQ4uQbBBtaVsdr6EffAqVmp3O5GyUANU2DoA3dJufNhDfh7KOlLgKIvRVhDxRESHLmea6fTE26gLUqKEUuuizJiLENrCbax94DZHDu8WhaXM9vQ86gzlqceNPO5w3vwXm4VrBF3x2lAMEl06wgNdTSMiT7cNG4HIdW0JxRNW4I7npH37okmOx1QXGktQC6RhsvAwtrGUBhvS0ypvLOee6as9H',
    publishedAt: '2026-09-12T16:00:00Z',
    bestFor: ['Compact kitchen worktops', 'Creating storage above a microwave', 'Keeping spices and light utensils within reach'],
    checks: ['Measure the microwave width, height and ventilation clearances.', 'Confirm the selected rack width and stated load limit.', 'Compare the final variant, delivered price and estimated arrival at checkout.'],
  },
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
