'use client';
/* oxlint-disable nextjs/no-img-element, nextjs/no-html-link-for-pages */
import {useState} from 'react';
import {instagramDestination} from '@/lib/tracking';
import {matchesDiscovery,categories,categoryLabel,discoveryMetadata} from '@/lib/catalog-discovery';
import type {Product} from '@/app/products';
type Find={record:{instagramPublicationId:string;trackingId:string;thumbnail?:string|null;caption?:string;hook?:string};product:Product};
export function InstagramStore({finds}:{finds:Find[]}){
 const [query,setQuery]=useState('');const [category,setCategory]=useState('');const latest=finds[0];
 const visible=finds.filter(({product,record})=>matchesDiscovery(product,{query,category},[record.caption,record.hook].join(' ')));
 const activeCategories=categories.filter(c=>finds.some(f=>matchesDiscovery(f.product,{category:c.id})));
 const card=({record,product}:Find,featured=false)=><article className={`product-card ${featured?'ig-featured':''}`} key={record.instagramPublicationId}><a className="ig-image" href={instagramDestination('https://cleverfindspicks.github.io',product.slug,record.trackingId)}><img src={record.thumbnail||product.displayImage} alt={product.shortName} width="1080" height="1920" loading={featured?'eager':'lazy'} onError={e=>{if(product.displayImage&&e.currentTarget.getAttribute('src')!==product.displayImage)e.currentTarget.src=product.displayImage;}}/></a><div className="product-body"><p className="eyebrow">{categoryLabel(discoveryMetadata(product).primaryCategory)}</p><h3>{product.shortName}</h3><p className="card-benefit">{product.summary}</p><a className="primary-link" href={instagramDestination('https://cleverfindspicks.github.io',product.slug,record.trackingId)}>{featured?'View this find':'View find'} →</a></div></article>;
 return <><section className="ig-latest"><h2>Latest Instagram Find</h2>{latest?card(latest,true):<p>No live Instagram finds yet. Test or deleted Reels do not appear here.</p>}</section><section className="ig-search"><label htmlFor="ig-search">Search the find you saw...</label><input id="ig-search" type="search" placeholder="Search the find you saw..." value={query} onChange={e=>setQuery(e.target.value)}/></section><section className="ig-more"><h2>Recent Instagram Finds</h2><div className="ig-grid">{(query||category?visible:finds.slice(1)).map(row=>card(row))}</div>{(query||category)&&!visible.length&&<output>No matching Instagram find.</output>}</section><section className="ig-categories"><h2>Browse by category</h2><div className="category-chips">{activeCategories.map(c=><button key={c.id} type="button" aria-pressed={category===c.id} onClick={()=>setCategory(category===c.id?'':c.id)}>{c.label}</button>)}</div>{!activeCategories.length&&<p>Categories appear after eligible Instagram finds are published.</p>}</section></>;
}
