'use client';
/* oxlint-disable nextjs/no-html-link-for-pages, nextjs/no-img-element */
import {useState} from 'react';
import type {Product} from '@/app/products';
import {categories,categoryLabel,discoveryMetadata,matchesDiscovery,type DiscoveryFilters} from '@/lib/catalog-discovery';
export function ProductCard({product,eager=false}:{product:Product;eager?:boolean}){
 const category=discoveryMetadata(product).primaryCategory;
 return <article className="product-card"><a className="product-image" href={`/finds/${product.slug}/`}><img src={product.displayImage} alt={product.shortName} width="700" height="700" loading={eager?'eager':'lazy'}/></a><div className="product-body"><p className="eyebrow">{categoryLabel(category)}</p><h3><a href={`/finds/${product.slug}/`}>{product.shortName}</a></h3><p className="card-benefit">{product.summary}</p>{product.currencyVerified&&typeof product.verifiedPriceGbp==='number'&&<p className="verified-price">From £{product.verifiedPriceGbp.toFixed(2)} <small>when checked · options may vary</small></p>}<a className="text-link" href={`/finds/${product.slug}/`}>View find →</a></div></article>;
}
export function ProductDiscovery({products,initialCategory=''}:{products:Product[];initialCategory?:string}){
 const [filters,setFilters]=useState<DiscoveryFilters>({category:initialCategory});
 const filtered=products.filter(p=>matchesDiscovery(p,filters));const active=!!(filters.query||filters.category||filters.room||filters.renterFriendly||filters.noDrill||filters.smallSpace||filters.maxPrice);
 const update=(patch:DiscoveryFilters)=>setFilters({...filters,...patch});
 const rooms=[...new Set(products.map(p=>discoveryMetadata(p).room))].sort();
 const available=categories.filter(c=>products.some(p=>matchesDiscovery(p,{category:c.id})));
 return <section className="discovery" aria-label="Find useful products"><div className="discovery-search"><label htmlFor="product-search">Find your next useful find</label><input id="product-search" type="search" placeholder="Search products..." value={filters.query||''} onChange={e=>update({query:e.target.value})}/></div>
 <details className="discovery-filters"><summary>Filter finds</summary><div className="filter-controls"><label>Category<select value={filters.category||''} onChange={e=>update({category:e.target.value})}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Room<select value={filters.room||''} onChange={e=>update({room:e.target.value})}><option value="">Any room</option>{rooms.map(r=><option key={r}>{r}</option>)}</select></label><label>Verified GBP price<select value={filters.maxPrice||''} onChange={e=>update({maxPrice:e.target.value?Number(e.target.value):null})}><option value="">Any / unknown price</option>{[10,25,50,100].map(v=><option key={v} value={v}>Up to £{v}</option>)}</select></label><div className="filter-checks">{(['renterFriendly','noDrill','smallSpace'] as const).map((key,i)=><label key={key}><input type="checkbox" checked={!!filters[key]} onChange={e=>update({[key]:e.target.checked})}/>{['Renter-friendly','No-drill mounting','Small-space'][i]}</label>)}</div><button type="button" onClick={()=>setFilters({})}>Clear filters</button></div><p className="filter-note">Price filters include only explicitly verified GBP prices. Mounting claims are shown only where known.</p></details>
 {!active&&products[0]&&<section className="latest-feature"><p className="eyebrow">LATEST FIND</p><h2>A useful place to start</h2><ProductCard product={products[0]} eager/></section>}
 <section className="browse-categories" id="categories"><h2>Browse by category</h2><div className="category-chips">{available.map(c=><button type="button" key={c.id} aria-pressed={filters.category===c.id} onClick={()=>update({category:filters.category===c.id?'':c.id})}>{c.label}</button>)}</div></section>
 <section className="finds discovery-results" id="finds"><div className="section-heading"><h2>{active?'Matching finds':'Latest verified products'}</h2><output aria-live="polite">{filtered.length} {filtered.length===1?'find':'finds'}</output></div><div className="product-grid">{filtered.map((p,i)=><ProductCard key={p.slug} product={p} eager={active&&i===0}/>)}</div>{!filtered.length&&<p className="empty-find">No verified finds match yet. Try another category or clear your filters.</p>}</section></section>;
}
